spring:
  datasource:
    url: jdbc:sqlserver://serv-converter.database.windows.net:1433;database=sql-db-converter;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: coverteradmin@serv-converter
    password: ${sql-db-pw}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

server:
  port: 8080

#coverteradmin@serv-converter